name: CI
on:
  - push
  - pull_request
jobs:

  build-node:
    needs:
      - lint-node
      - lint-python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 16.x
          - 18.x
          - 20.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable corepack
        run: corepack enable
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
 
  lint-node:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Enable corepack
        run: corepack enable
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run linter
        run: yarn lint

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Use Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v3
        with:
          path: '**/.venv'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
      - name: Run linter
        run: python -m pylint
